DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS catalog;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	rank INTEGER NOT NULL,
	coins INTEGER NOT NULL,
	avatar TEXT
);

CREATE TABLE blog (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	title TEXT UNIQUE NOT NULL,
	body TEXT NOT NULL
);

CREATE TABLE catalog (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	type INTEGER NOT NULL,
	price INTEGER
);